### ISSUE TITLE
Fails to expand at the very beginning or end of a buffer

### ISSUE THREAD

**Issue by doublep** [xFA25E/skempo#2]
Using an example template:

    (skempo-define-tempo (let :mode (emacs-lisp-mode lisp-mode))
      (lisp-with-parens
       "let ((" p "))" n>
       r>))

1) create a new buffer;
2) type "let";
3) press `C-z` or `M-x skempo-complete-tag-or-call-on-region RET`.

Fails with "Wrong type argument: number-or-marker-p, nil" here.

On a tangentially related note, I suggest you add some tests.

**Comment by xFA25E** [comment]
Hi, thanks for reporting this issue!

This issue, however, is not directly related to this project. This is a bug in my emacs configuration. I've just fixed it [here](https://github.com/xFA25E/nixpkgs-config/commit/c35e9d729cb9d208b7df155bfe1467e995127695).

Tests would be a great idea. I can't figure out, how to test interactive template expansion.
